### ISSUE TITLE
Ajuste no UI de configurações

### ISSUE THREAD

**Issue by mateusfg7** [NyctibiusVII/BoletimEscolar#2]
Ficaria visualmente mais agradável se o ícone fosse alinhado à direita do título, colados na borda direita, ao invés de ficar colado no título em sí.

![image](https://github.com/NyctibiusVII/BoletimEscolar/assets/40613276/7942adf0-361b-4ab4-9bf5-9e0d6b76a227)

**Comment by NyctibiusVII** [comment]
Olá, obrigado por interagir!

Eu concordo com você, há um tempo atrás tentei fazer isso mas não consegui e acabei por deixar assim mesmo. Agora, com mais experiência posso tentar novamente!

Penso em alinhar o ::marker á lateral como você disse, assim:

![image](https://github.com/NyctibiusVII/BoletimEscolar/assets/52816125/b101f793-32f5-4fe8-9378-bc2c4dd4cba5)

**Comment by mateusfg7** [comment]
Exato, porem direcionando a ponta do triângulo para a direita, e quando aberto ele gira pra baixo.
